# Generated by Django 4.1.13 on 2023-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"default_manager_name": "objects", "ordering": ["-publish"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255, unique_for_date="publish"),
        ),
    ]
